version: 2
updates:
  - package-ecosystem: pip
    directory: custom
    schedule:
      interval: daily
      time: '04:00'
    ignore:
      - dependency-name: none

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    ignore:
      - dependency-name: none
  - package-ecosystem: docker
    directory: '/custom'
    schedule:
      interval: daily
    ignore:
      - dependency-name: none
  - package-ecosystem: pip
    directory: '/custom'
    schedule:
      interval: daily
    ignore:
      - dependency-name: none
