# https://pre-commit.com/hooks.html

exclude: |
  (?x)^(
    CONST_.*
    |mapserver/data/lac-leman.osm
  )$

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args:
          - --markdown-linebreak-ext=.md
      - id: mixed-line-ending
        args:
          - --fix=lf
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        exclude: |-
          (?x)^(
            geoportal/geomapfish_geoportal/static-ngeo/js/apps/Controller.*.js
            |geoportal/webpack.apps.js
          )$
  - repo: https://github.com/sbrunner/integrity-updater
    rev: 0.2.0
    hooks:
      - id: integrity-updater
        include: |-
          (?x)^(
            geoportal/geomapfish_geoportal/static/.*
            |ui/.*
          )$
        args:
          - --pre-commit
          - --blacklist=https://maps\.googleapis\.com/
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        exclude: |-
          (?x)^(
            geoportal/.*
          )$
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.16.0
    hooks:
      - id: pyupgrade
        args:
          - --py310-plus
        exclude: |-
          (?x)^(
            build
          )$
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: detect-private-key
      - id: check-merge-conflict
      - id: check-ast
      - id: debug-statements
      - id: check-toml
      - id: check-yaml
      - id: check-json
        exclude: |-
          (?x)^(
            ui/tsconfig\.json
          )$
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
  - repo: https://github.com/sbrunner/hooks
    rev: 1.0.0
    hooks:
      - id: copyright
        exclude: |-
          (?x)^(
            build
            |geoportal
            |scripts/db-backup
            |scripts/db-restore
          )$
      - id: poetry-lock
        additional_dependencies:
          - poetry==1.8.3 # pypi
        exclude: |-
          (?x)^(
            pyproject\.toml
          )$
  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        exclude: |-
          (?x)^(
            (.*/)?poetry\.lock
            |(.*/)?package-lock\.json
            |ci/cleanup
            |geoportal/geomapfish_geoportal/locale/.*
            |qgisserver/.*\.qg[sz]
            |geoportal/geomapfish_geoportal/static/story-map\.html
            |tilegeneration/config\.yaml\.tmpl
            |webcomponents/feedback\.ts
            |ui/src/webcomponents/feedback\.ts
          )$
        args:
          - --ignore-words=.github/spell-ignore-words.txt
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: git-check
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.28.6
    hooks:
      - id: check-github-actions
      - id: check-github-workflows
      - id: check-jsonschema
        name: Check GitHub Workflows set timeout-minutes
        files: ^\.github/workflows/[^/]+$
        types:
          - yaml
        args:
          - --builtin-schema
          - github-workflows-require-timeout
  - repo: https://github.com/sirwart/ripsecrets
    rev: v0.1.8
    hooks:
      - id: ripsecrets
  - repo: https://github.com/sbrunner/jsonschema-validator
    rev: 0.1.0
    hooks:
      - id: jsonschema-validator
        files: ^ci/config\.yaml$
  - repo: https://github.com/renovatebot/pre-commit-hooks
    rev: 37.428.1
    hooks:
      - id: renovate-config-validator
