# https://pre-commit.com/hooks.html

exclude: |-
  (?x)^(
    CONST_.*
    |mapserver/data/lac-leman\.osm
    |(CONST_create_template/|)geoportal/geomapfish_geoportal/static-ngeo/js/apps/Controller.*\.js
    |(CONST_create_template/|)geoportal/geomapfish_geoportal/static-ngeo/js/apps/.*\.html\.ejs
    |(CONST_create_template/|)geoportal/geomapfish_geoportal/static-ngeo/js/apps/sass/.*
    |(CONST_create_template/|)geoportal/geomapfish_geoportal/static-ngeo/js/apps/image/.*
    |(CONST_create_template/|)geoportal/geomapfish_geoportal/static-ngeo/api/api\.css
    |(CONST_create_template/|)geoportal/geomapfish_geoportal/static-ngeo/api/index\.js
    |(CONST_create_template/|)print/print-apps/demo/.*\.jrxml
    |(CONST_create_template/|)scripts/(db-backup|db-restore|multi-tenant-update-po|qgis-project-download|qgis-project-upload)
  )$

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: detect-private-key
      - id: end-of-file-fixer
        exclude: |-
          (?x)^(
            ui/package\.json
          )$
      - id: trailing-whitespace
        args:
          - --markdown-linebreak-ext=.md
      - id: mixed-line-ending
        args:
          - --fix=lf
      - id: check-merge-conflict
      - id: check-ast
      - id: debug-statements
      - id: check-toml
      - id: check-yaml
      - id: check-json
        exclude: |-
          (?x)^(
            ui/tsconfig\.json
            |geogirafe/tsconfig\.json
            |geogirafe/CONST_scaffold/tsconfig\.json
          )$
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        exclude: |-
          (?x)^(
            geoportal/geomapfish_geoportal/static-ngeo/js/apps/Controller.*\.js
            |geoportal/webpack\.apps\.js
            |ui/package\.json
          )$
  - repo: https://github.com/sbrunner/integrity-updater
    rev: 1.0.2
    hooks:
      - id: integrity-updater
        files: |-
          (?x)^(
            geoportal/geomapfish_geoportal/static/.*
            |ui/.*
          )$
        args:
          - --pre-commit
          - --blacklist=https://maps\.googleapis\.com/
  - repo: https://github.com/sbrunner/hooks
    rev: 1.8.0
    hooks:
      - id: copyright
        exclude: |-
          (?x)^(
            build
            |geoportal
            |scripts/db-backup
            |scripts/db-restore
          )$
      - id: poetry2-lock
        additional_dependencies:
          - poetry==2.4.1 # pypi
        exclude: |-
          (?x)^(
            pyproject\.toml
          )$
        language_version: '3.13'
      - id: npm-lock
        exclude: |-
          (?x)^(
            geogirafe/CONST_scaffold/package\.json
          )$
      - id: canonicalize
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.3
    hooks:
      - id: codespell
        exclude: |-
          (?x)^(
            (.*/)?poetry\.lock
            |(.*/)?package-lock\.json
            |ci/cleanup
            |geoportal/geomapfish_geoportal/locale/.*
            |qgisserver/.*\.qg[sz]
            |geoportal/geomapfish_geoportal/static/story-map\.html
            |tilegeneration/config\.yaml\.tmpl
            |geogirafe/.*
          )$
        args:
          - --ignore-words=.github/spell-ignore-words.txt
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.11.0.1
    hooks:
      - id: shellcheck
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.37.4
    hooks:
      - id: check-github-actions
      - id: check-github-workflows
      - id: check-jsonschema
        name: Check GitHub Workflows set timeout-minutes
        files: ^\.github/workflows/[^/]+$
        types:
          - yaml
        args:
          - --builtin-schema
          - github-workflows-require-timeout
  - repo: https://github.com/sirwart/ripsecrets
    rev: v0.1.11
    hooks:
      - id: ripsecrets
  - repo: https://github.com/sbrunner/jsonschema-validator
    rev: 1.0.0
    hooks:
      - id: jsonschema-validator
        files: |-
          (?x)^(
            \.github/publish\.yaml
            |\.github/ghci\.yaml
            |CONST_create_template/ci/config\.yaml
            |ci/config\.yaml
          )$
  - repo: https://github.com/renovatebot/pre-commit-hooks
    rev: 43.288.0
    hooks:
      - id: renovate-config-validator
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.1
    hooks:
      - id: ruff-format
  - repo: https://github.com/sbrunner/python-versions-hook
    rev: 1.3.0
    hooks:
      - id: python-versions
