# https://pre-commit.com/hooks.html

ci:
  autoupdate_schedule: quarterly
  skip:
    - jsonschema-validator
repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@2.8.4
  - repo: https://github.com/sbrunner/jsonschema-validator
    rev: 0.1.0
    hooks:
      - id: jsonschema-validator
        files: ^ci/config\.yaml$
