---

sudo: false

addons:
  apt:
    packages:
      - python3-netifaces

env:
  global:
    - DOCKER_USERNAME=dockerhubc2c
    - secure: "vpSNV7FOz6TaULaqqEfviKizsUnROqBKGEurvM2D/02mQQgINl5BRDuZMyCiPB+m96hbbO4IDxuO3r9Fvnsn3faDrze/z\
        jKC+/npztumqNYr8wSDwwwiArQQrYbY+nSQoswv5xYPKVRhTKsbtvYHqIG3c+1cgSQ5ODsvbZTWQXM="
    - OPENSHIFT_URL=https://api.openshift-ch-3.camptocamp.com/

jobs:
  include:
    - stage: config-geoportal
      script:
        - ./docker-run make docker-build-config
      after_success:
        - ./travis/deploy 2.4 config
    - script:
        - ./docker-run make checks
        - ./docker-run make docker-build-geoportal
      after_success:
        - ./travis/deploy 2.4 geoportal
