---
sudo: false

addons:
  apt:
    packages:
      - python3-netifaces

env:
  global:
    - PROJECT=demo
    - OPENSHIFT_PROJECT=gs-gmf-demo
    - HELM_RELEASE_NAMES=2.4 # List of branch that should be deployed on helm
    - DOCKER_USERNAME=dockerhubc2c
    - secure: "vpSNV7FOz6TaULaqqEfviKizsUnROqBKGEurvM2D/02mQQgINl5BRDuZMyCiPB+m96hbbO4IDxuO3r9Fvnsn3faDrze/z\
        jKC+/npztumqNYr8wSDwwwiArQQrYbY+nSQoswv5xYPKVRhTKsbtvYHqIG3c+1cgSQ5ODsvbZTWQXM="
    - OPENSHIFT_URL=https://api.openshift-ch-1.camptocamp.com/

jobs:
  include:
    - stage: config-geoportal
      script:
        - ./docker-run make docker-build-config
      after_success:
        - ./scripts/deploy-docker --image=config
    - script:
        - ./docker-run make checks
        - ./docker-run make docker-build-geoportal
      after_success:
        - ./scripts/deploy-docker --image=geoportal
