---
# This file can be renamed as `docker-compose.override.yaml` and uncomment the desired lines for
# development. The file `docker-compose.override.yaml` is ignored by Git by default.

# yamllint disable rule:line-length

version: '2'

services:
  geoportal:
    user: root
    volumes:
      # For Python project development.
      - ${PWD}/geoportal/geomapfish_geoportal:/app/geomapfish_geoportal
      # For Python c2cgeportal development.
      # - '${PWD}/../c2cgeoportal/commons/c2cgeoportal_gcommons:/opt/c2cgeoportal/commons/c2cgeoportal_commons'
      # - '${PWD}/../c2cgeoportal/geoportal/c2cgeoportal_geoportal:/opt/c2cgeoportal/geoportal/c2cgeoportal_geoportal'
      # - '${PWD}/../c2cgeoportal/admin/c2cgeoportal_admin:/opt/c2cgeoportal/admin/c2cgeoportal_admin'
      # - '${PWD}/../c2cwsgiutils/c2cwsgiutils:/opt/c2cwsgiutils/c2cwsgiutils'
      # - '${PWD}/../c2cgeoform/c2cgeoform:/usr/local/lib/python3.7/dist-packages/c2cgeoform'
    command: mprof run --include-children /usr/local/bin/gunicorn $GUNICORN_PARAMS c2cwsgiutils.wsgi_app:application
    environment:
      - GUNICORN_CMD_ARGS=--reload
      - C2CWSGIUTILS_CONFIG=/app/development.ini
      # - PRINT_URL=http://print:8080/print/
    ports:
      - 5678:5678  # For remote debugging using Visual Studio Code

  # Also uncomment the PRINT_URL in geoportal
  # print:
  #   extends:
  #     file: docker-compose-lib.yaml
  #     service: print
  #   volumes_from:
  #     - config:ro

  # qgisserver:
  #   environment:
  #     env:
  #       - QGIS_SERVER_LOG_LEVEL=0

  # For Javascript project development.
  # The debug application will be availavble at ``https://<host>/<entry_point>/dev/<interface>.html``.
  webpack_dev_server:
    # Uncomment these lines when you want to debug respectively the project js, ngeo js and/or the gmf contrib js.
    # Adapt the path for ngeo / gmf contrib to point where you have checkouted the code.
    # volumes:
    #   - ${PWD}/geoportal/geomapfish_geoportal/static-ngeo:/app/geomapfish_geoportal/static-ngeo
    #   - ${PWD}/../ngeo/src:/usr/lib/node_modules/ngeo/src
    #   - ${PWD}/../ngeo/contribs:/usr/lib/node_modules/ngeo/contribs
    volumes_from:
      - config:rw
    extends:
      file: docker-compose-lib.yaml
      service: webpack_dev_server
