---
# This file can be renamed as `docker-compose.override.yaml` and uncomment the desired lines for
# development. The file `docker-compose.override.yaml` is ignored by Git by default.

version: '2.3'

services:
  db:
    extends:
      file: docker-compose-lib.yaml
      service: db
    volumes:
      - postgresql_data:/var/lib/postgresql/data
