# This file can be renamed as `docker-compose.override.yaml` and uncomment the desired lines for
# development. The file `docker-compose.override.yaml` is ignored by Git by default.

services:
  # config:
  #   volumes:
  #       # www-data should be able to write in qgisserver
  #     - './qgisserver:/etc/qgisserver/'

  geoportal:
    user: root
    volumes:
      []
      # For Python project development.
      # - ./geoportal/${PACKAGE}_geoportal:/app/${PACKAGE}_geoportal
      # For Python c2cgeportal development.
      # - ./../c2cgeoportal/commons/c2cgeoportal_commons:/opt/c2cgeoportal/commons/c2cgeoportal_commons
      # - ./../c2cgeoportal/geoportal/c2cgeoportal_geoportal:/opt/c2cgeoportal/geoportal/c2cgeoportal_geoportal
      # - ./../c2cgeoportal/admin/c2cgeoportal_admin:/opt/c2cgeoportal/admin/c2cgeoportal_admin
      # - ./../c2cgeoportal/bin:/opt/bin
      # - ./../c2cwsgiutils/c2cwsgiutils:/usr/local/lib/python3.8/dist-packages/c2cwsgiutils
      # - ./../dogpile.cache/dogpile:/usr/local/lib/python3.8/dist-packages/dogpile
      # - ./../c2c.template/c2c/template:/usr/local/lib/python3.8/dist-packages/c2c/template
    command:
      - /usr/local/bin/pserve
      - --reload
      - c2c:///app/development.ini
    environment:
      - DEVELOPMENT=1
      - C2C_SQL_PROFILER_ENABLED=1
      - C2C_DEBUG_VIEW_ENABLED=1
      - C2CGEOPORTAL_LOG_LEVEL=DEBUG
      # - PRINT_URL=http://print:8080/print/
      - PYTHONWARNINGS=default::DeprecationWarning
      - SQLALCHEMY_WARN_20=true
    ports:
      - 5678:5678 # For remote debugging using Visual Studio Code

  # Also uncomment the PRINT_URL in geoportal
  # print:
  #   extends:
  #     file: docker-compose-lib.yaml
  #     service: print
  #   volumes_from:
  #     - config:ro
  #   environment:
  #     - LOG_LEVEL=DEBUG

  # qgisserver:
  #   # volumes:
  #   #   - './../c2cgeoportal/docker/qgisserver/geomapfish_qgisserver/:/var/www/plugins/geomapfish_qgisserver/'
  #   #   - './../c2cgeoportal/commons/c2cgeoportal_commons:/opt/c2cgeoportal/commons/c2cgeoportal_commons/'
  #   environment:
  #     - QGIS_SERVER_LOG_LEVEL=0
  #     - QGIS_CATCH_SEGV=1 # The result stack traces will be available in /var/log/qgis.log

  # For Javascript project development.
  # The debug application will be available at ``https://<host>/<entry_point>/dev/<interface>.html``.
  # webpack_dev_server:
  #   # Uncomment these lines when you want to debug respectively the project js, ngeo js and/or the gmf contrib js.
  #   # Adapt the path for ngeo / gmf contrib to point where you have checkouted the code.
  #   # volumes:
  #   #   - ./geoportal/${PACKAGE}_geoportal/static-ngeo:/app/${PACKAGE}_geoportal/static-ngeo
  #   #   - ./../ngeo/src:/opt/c2cgeoportal/geoportal/node_modules/ngeo/src
  #   #   - ./../ngeo/contribs:/opt/c2cgeoportal/geoportal/node_modules/ngeo/contribs
  #   volumes_from:
  #     - config:rw
  #   extends:
  #     file: docker-compose-lib.yaml
  #     service: webpack_dev_server

  tilecloudchain:
    # volumes:
    #   - ../tilecloud-chain/tilecloud_chain:/app/tilecloud_chain
    #   - ../tilecloud/tilecloud:/usr/local/lib/python3.8/dist-packages/tilecloud
    #   - ../c2cwsgiutils/c2cwsgiutils:/usr/local/lib/python3.8/dist-packages/c2cwsgiutils
    command:
      - gunicorn
      - --reload
      - --paste=/app/production.ini
    environment:
      - TILECLOUD_CHAIN_LOG_LEVEL=DEBUG

  tilegeneration_slave:
    # volumes:
    #   - ../tilecloud-chain/tilecloud_chain:/app/tilecloud_chain
    #   - ../tilecloud/tilecloud:/usr/local/lib/python3.7/dist-packages/tilecloud
    #   - ../c2cwsgiutils/c2cwsgiutils:/usr/local/lib/python3.8/dist-packages/c2cwsgiutils
    environment:
      - TILECLOUD_CHAIN_LOG_LEVEL=DEBUG

  tools:
    volumes_from:
      - config:rw
    volumes:
      - .:/src

  custom:
    command:
      - /usr/local/bin/pserve
      - --reload
      - c2c://development.ini
    volumes:
      - ./custom/custom:/app/custom
