---
project_folder: demo_geomapfish
project_package: demo
application_url: https://localhost:8484/
checker_url: https://172.17.0.1:8484/c2c/health_check?max_level=9
managed_files:
  - spell-ignore-words\.txt
  - Makefile
  - \.gitignore
unmanaged_files:
  - geoportal/demo_geoportal/static-ngeo/js/apps/Controller.*\.js
  - geoportal/demo_geoportal/static-ngeo/js/apps/.*\.html\.ejs
  - geoportal/demo_geoportal/static-ngeo/js/apps/sass/.*
  - geoportal/demo_geoportal/static-ngeo/js/apps/image/.*
  - geoportal/demo_geoportal/static/apihelp/.*
  - print/print-apps/demo/.*\.jrxml
  - geoportal/demo_geoportal/static-ngeo/api/index.js
template_vars:
  package: demo
  srid: 21781
  extent: 489246,78873,837119,296543
