[tool.black]
line-length = 110
target-version = ['py39']

[tool.isort]
profile = "black"
line_length = 110

[tool.poetry]
name = "demo_geomapfish"
version = "0.0.0"
description = "Demo of GeoMapFish Application"
authors = ["Camptocamp <info@camptocamp.com>"]
