[tool.black]
line-length = 110
target-version = ['py39']

[tool.isort]
profile = "black"
line_length = 110

[tool.poetry]
name = "GeoMapFish demo"
version = "0.0.0"
description = "GeoMapFish demo"
authors = ["Camptocamp"]
