---
name: Rebuild

on:
  schedule:
    - cron: '30 2 * * *'

env:
  PROJECT: geomapfish
  # Requires CI_GPG_PRIVATE_KEY and GOPASS_CI_GITHUB_TOKEN secrets.
  # OPENSHIFT_PROJECT: gs-gmf-geomapfish
  # The release branches
  HELM_RELEASE_NAMES: int-2-8,prod-2-8

jobs:
  rebuild:
    runs-on: ubuntu-20.04
    name: Rebuild
    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:
        branch:
          - int-2-8
          - prod-2-8

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ matrix.branch }}

      - uses: camptocamp/initialise-gopass-summon-action@v2
        with:
          ci-gpg-private-key: ${{ secrets.CI_GPG_PRIVATE_KEY }}
          github-gopass-ci-token: ${{ secrets.GOPASS_CI_GITHUB_TOKEN }}
          patterns: docker

      - run: echo "${HOME}/.local/bin" >> ${GITHUB_PATH}
      - run: python3 -m pip install --user --requirement=ci/requirements.txt

      - name: Build
        run: ./build

      - name: Publish
        run: c2cciutils-publish --branch=${{ matrix.branch }} --type=rebuild
