inherits:
  - duplicated
  - utils:base-less-strict

mypy:
  options:
    python-version: '3.12'

ruff:
  options:
    target-version: py312
    per-file-ignores: 'geomapfish_geoportal/dev.py=T100,geomapfish_geoportal/resources.py=RUF012'
