#!/usr/bin/env python3
import os
import sys

import boto3

BUCKET = sys.argv[1]
PREFIX = sys.argv[2]


def main():
    session = boto3.session.Session()

    s3_client = session.client(
        service_name="s3",
        endpoint_url=f"https://{os.environ['AWS_S3_ENDPOINT']}/",
        region_name=os.environ["AWS_DEFAULT_REGION"],
    )
    keys = [i["Key"] for i in s3_client.list_objects(Bucket=BUCKET, Prefix=PREFIX)["Contents"]]
    filtered_keys = list(filter(lambda i: i.endswith(".bt") or i.endswith(".tif"), keys))
    full_keys = [f"/vsis3/{BUCKET}/{i}" for i in filtered_keys]
    print("\n".join(full_keys))


main()
