# Language provided by the application
LANGUAGES ?= en fr de it
NGEO_INTERFACES ?= desktop mobile iframe_api
NGEO_API ?= TRUE

# SRC_FILES ?= $(shell find $(PACKAGE)_geoportal -name "*.py" -print 2> /dev/null)

include CONST_Makefile
