inherits:
  - utils:base
  - utils:fix
  - utils:no-design-checks
  - utils:c2cwsgiutils
  - duplicated

mypy:
  run: false
  options:
    python_version: '3.10'

ruff:
  disable:
    - CPY001 # Missing copyright notice
    - D101 # Missing docstring in public class
    - D102 # Missing docstring in public method
    - D103 # Missing docstring in public function
