inherits:
  - utils:base
  - utils:fix
  - utils:no-design-checks
  - duplicated

pylint:
  disable:
    - import-error # Runtime dependencies not available in linting container

mypy:
  run: false
  options:
    python_version: '3.10'

ruff:
  disable:
    - D101 # Missing docstring in public class
    - D102 # Missing docstring in public method
    - D103 # Missing docstring in public function
