inherits:
  - utils:base
  - utils:fix
  - utils:no-design-checks
  - duplicated

pylint:
  disable:
    - missing-timeout # Default timeout set by c2cwsgiutils

bandit:
  options:
    config: .bandit.yaml
