version: 1
disable_existing_loggers: false

formatters:
  generic:
    class: logging.Formatter
    format: '%(levelname)-5.5s %(name)s %(message)s'
    datefmt: '[%Y-%m-%d %H:%M:%S %z]'

handlers:
  console:
    class: logging.StreamHandler
    formatter: generic

loggers:
  uvicorn.error:
    level: INFO

  uvicorn.access:
    level: INFO

  sqlalchemy.engine:
    level: WARNING

  c2casgiutils:
    level: WARNING

  custom:
    level: DEBUG

root:
  level: WARNING
  handlers:
    - console
