[tool.poetry]
name = 'demo-geomapfish-custom'
version = '0.0.0'
description = 'Not used'
authors = []

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
gunicorn = "20.1.0"
plaster-pastedeploy = "1.0.1"
pyramid = "2.0"
pyramid-mako = "1.1.0"
pyramid-debugtoolbar = "4.9"
waitress = "2.1.2"
alembic = "1.8.1"
pyramid-retry = "2.1.1"
pyramid-tm = "2.5"
sqlalchemy = "1.4.44"
transaction = "3.0.1"
"zope.sqlalchemy" = "1.6"
cornice = "6.0.1"
requests = "2.28.1"
psycopg2 = "2.9.5"
c2cwsgiutils = "5.1.5"
cee-syslog-handler = "0.6.0"
PyJWT = "2.6.0"
redis = "4.3.4"
PyYAML = "6.0"
sentry-sdk = "1.10.1"
requests-oauthlib = "1.3.1"
ujson = "5.5.0"

[tool.poetry.dev-dependencies]
prospector = { version = "1.7.7", extras = ["with_bandit", "with_mypy"] }
