[tool.poetry.dependencies]
python = ">=3.12,<3.14"
alembic = "1.18.5"
azure-identity = "1.25.3"
azure-storage-blob = "12.30.0"
c2casgiutils = "0.14.0"
fastapi = "0.141.1"
geojson = "3.3.0"
oauthlib = "3.3.0"
prometheus-fastapi-instrumentator = "8.1.0"
pydantic = "2.13.4"
pydantic-settings = "2.15.0"
requests = "2.34.2"
requests-oauthlib = "2.0.0"
sentry-sdk = "2.66.1"
sqlalchemy = "2.0.51"
uvicorn = { version = "0.52.4", extras = ["standard"] }
# To fix CVE
urllib3 = "2.7.0"
certifi = { version = "2026.7.22", optional = true }
cryptography = "50.0.0"
idna = "3.18"

[tool.poetry.group.dev.dependencies]
prospector = { version = "1.19.1", extras = ["with_bandit", "with_mypy", "with_pyroma", "with_ruff"] }
prospector-profile-utils = "1.27.0"
prospector-profile-duplicated = "1.12.0"
types-requests = "2.33.0.20260712"
types-oauthlib = "3.3.0.20260724"
ruff = "0.15.20"
pylint = "4.0.6"

[tool.pylint]
disable = ["import-error"]

[project]
name = 'demo-geomapfish-custom'
version = '0.0.0'
description = 'Not used'
authors = []

[project.scripts]
custom-initialize-db = "custom.scripts.initialize_db:main"

[project.entry-points."paste.app_factory"]
main = "custom:main"
