[tool.poetry]
name = 'demo-geomapfish-custom'
version = '0.0.0'
description = 'Not used'
authors = []

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
gunicorn = "20.1.0"
plaster-pastedeploy = "0.7"
pyramid = "2.0.2"
pyramid-mako = "1.1.0"
pyramid-debugtoolbar = "4.9"
waitress = "2.1.2"
alembic = "1.7.7"
pyramid-retry = "2.1.1"
pyramid-tm = "2.5"
sqlalchemy = "1.4.51"
transaction = "3.0.1"
"zope.sqlalchemy" = "1.6"
cornice = "6.0.1"
requests = "2.27.1"
psycopg2 = "2.9.9"
c2cwsgiutils = "5.0.2"
cee-syslog-handler = "0.6.0"
PyJWT = "2.4.0"
redis = "4.3.6"
PyYAML = "6.0.1"
sentry-sdk = "1.5.12"
requests-oauthlib = "1.3.1"
ujson = "5.3.0"


[tool.poetry.dev-dependencies]
prospector = {version = "1.7.7", extras = ["with_bandit", "with_mypy"]}
