[tool.poetry]
name = 'demo-geomapfish-custom'
version = '0.0.0'
description = 'Not used'
authors = []

[tool.poetry.dependencies]
python = ">=3.12,<3.14"
gunicorn = "23.0.0"
plaster-pastedeploy = "1.0.1"
pyramid = "2.0.2"
pyramid-mako = "1.1.0"
pyramid-debugtoolbar = "4.12.1"
waitress = "3.0.2"
alembic = "1.14.1"
pyramid-retry = "2.1.1"
pyramid-tm = "2.6"
sqlalchemy = "2.0.41"
transaction = "5.0"
"zope.sqlalchemy" = "3.1"
cornice = "6.1.0"
requests = "2.32.4"
psycopg2 = "2.9.10"
c2cwsgiutils = { version = "6.1.7", extras = ["webserver"] }
cee-syslog-handler = "0.6.0"
PyJWT = "2.10.1"
redis = "5.2.1"
PyYAML = "6.0.2"
sentry-sdk = "2.19.2"
requests-oauthlib = "2.0.0"
ujson = "5.10.0"
azure-storage-blob = "12.24.1"
azure-identity = "1.19.0"
papyrus = "2.6.2"
geojson = "3.2.0"
# To fix CVE
urllib3 = "2.5.0"
certifi = { version = "2024.12.14", optional = true }
webob = { version = "1.8.9", optional = true }
cryptography = { version = "44.0.3", optional = true }

[tool.poetry.group.dev.dependencies]
prospector = { version = "1.13.3", extras = ["with_bandit", "with_mypy", "with_pyroma", "with_ruff"] }
prospector-profile-utils = "1.14.1"
prospector-profile-duplicated = "1.9.0"
types-requests = "2.32.4.20250611"
types-oauthlib = "3.2.0.20250516"
