[tool.poetry]
name = 'demo-geomapfish-custom'
version = '0.0.0'
description = 'Not used'
authors = []

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
gunicorn = "20.1.0"
plaster-pastedeploy = "1.0.1"
pyramid = "2.0.1"
pyramid-mako = "1.1.0"
pyramid-debugtoolbar = "4.10"
waitress = "2.1.2"
alembic = "1.9.4"
pyramid-retry = "2.1.1"
pyramid-tm = "2.5"
sqlalchemy = "2.0.4"
transaction = "3.0.1"
"zope.sqlalchemy" = "2.0"
cornice = "6.0.1"
requests = "2.28.2"
psycopg2 = "2.9.5"
c2cwsgiutils = "5.2.1"
cee-syslog-handler = "0.6.0"
PyJWT = "2.6.0"
redis = "4.5.1"
PyYAML = "6.0"
sentry-sdk = "1.16.0"
requests-oauthlib = "1.3.1"
ujson = "5.7.0"

[tool.poetry.dev-dependencies]
prospector = { version = "1.9.0", extras = ["with_bandit", "with_mypy"] }
