[tool.poetry]
name = 'demo-geomapfish-custom'
version = '0.0.0'
description = 'Not used'
authors = []

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
gunicorn = "21.2.0"
plaster-pastedeploy = "1.0.1"
pyramid = "2.0.2"
pyramid-mako = "1.1.0"
pyramid-debugtoolbar = "4.10"
waitress = "2.1.2"
alembic = "1.12.1"
pyramid-retry = "2.1.1"
pyramid-tm = "2.5"
sqlalchemy = "2.0.23"
transaction = "3.1.0"
"zope.sqlalchemy" = "3.1"
cornice = "6.0.1"
requests = "2.31.0"
psycopg2 = "2.9.9"
c2cwsgiutils = "6.0.4"
cee-syslog-handler = "0.6.0"
PyJWT = "2.8.0"
redis = "5.0.1"
PyYAML = "6.0.1"
sentry-sdk = "1.33.1"
requests-oauthlib = "1.3.1"
ujson = "5.8.0"

[tool.poetry.dev-dependencies]
prospector = { version = "1.10.3", extras = ["with_bandit", "with_mypy"] }
