[tool.poetry]
name = 'custom'
version = '0.0.0'
description = 'Custom package for GeoMapFish demo'
authors = []

[tool.poetry.scripts]
custom-initialize-db = "custom.scripts.initialize_db:main"

[tool.poetry.plugins."paste.app_factory"]
main = "custom:main"

[tool.poetry.dependencies]
python = ">=3.12,<3.14"
gunicorn = "23.0.0"
plaster-pastedeploy = "1.0.1"
pyramid = "2.0.2"
pyramid-mako = "1.1.0"
pyramid-debugtoolbar = "4.12.1"
waitress = "3.0.2"
alembic = "1.17.0"
pyramid-retry = "2.1.1"
pyramid-tm = "2.6"
sqlalchemy = "2.0.44"
transaction = "5.0"
"zope.sqlalchemy" = "4.0"
cornice = "6.1.0"
requests = "2.32.5"
psycopg2 = "2.9.11"
c2cwsgiutils = { version = "6.1.8", extras = ["webserver"] }
cee-syslog-handler = "0.6.0"
PyJWT = "2.10.1"
redis = "7.0.1"
PyYAML = "6.0.3"
sentry-sdk = "2.42.1"
requests-oauthlib = "2.0.0"
ujson = "5.11.0"
azure-storage-blob = "12.27.0"
azure-identity = "1.25.1"
papyrus = "2.6.2"
geojson = "3.2.0"
# To fix CVE
urllib3 = "2.5.0"
certifi = { version = "2025.11.12", optional = true }
webob = { version = "1.8.9", optional = true }
cryptography = { version = "46.0.3", optional = true }

[tool.poetry.dev-dependencies]
prospector = { version = "1.17.3", extras = ["with_bandit", "with_mypy", "with_pyroma", "with_ruff"] }
prospector-profile-utils = "1.26.5"
prospector-profile-duplicated = "1.10.5"
types-requests = "2.32.4.20250913"
types-oauthlib = "3.3.0.20250822"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
