#!/bin/bash -ax

docker tag camptocamp/demo-config:$1 camptocamp/demo-config:2.4
docker tag camptocamp/demo-geoportal:$1 camptocamp/demo-geoportal:2.4

mv docker-compose.yaml{,.bak}
./docker-run rm /build/c2ctemplate-cache.json
./docker-run make --makefile=prod.mk docker-compose.yaml
./docker-run rm /build/c2ctemplate-cache.json
mkdir -p /var/www/vhosts/geomapfish-demo/private/2.4
cp docker-compose.yaml /var/www/vhosts/geomapfish-demo/private/2.4/
cd /var/www/vhosts/geomapfish-demo/private/2.4
docker-compose down
docker-compose up -d
cd -
rm docker-compose.yaml
mv docker-compose.yaml{.bak,}
