#!/bin/bash -ax

docker tag camptocamp/demo-config:$1 camptocamp/demo-config:2.4
docker tag camptocamp/demo-geoportal:$1 camptocamp/demo-geoportal:2.4

mv .env{,.bak}
./docker-run rm /build/c2ctemplate-cache.json
./docker-run make --makefile=prod.mk .env
./docker-run rm /build/c2ctemplate-cache.json
mkdir -p /var/www/vhosts/geomapfish-demo/private/2.4
cp docker-compose.yaml .env /var/www/vhosts/geomapfish-demo/private/2.4/
cd /var/www/vhosts/geomapfish-demo/private/2.4
docker-compose down
docker-compose up -d
cd -
rm .env
mv .env{.bak,}
