#!/bin/bash -ex

git config user.email "<ci@camptocamp.com>"
git config user.name "Continuous integration"
./build --upgrade $1

if [ -e .UPGRADE7 ]
then
    ./upgrade $1 8
fi
if [ -e .UPGRADE8 ]
then
    # Workaround
    git status > /dev/null
    git apply --3way ngeo.diff
    ./upgrade $1 9
fi
if [ -e .UPGRADE9 ]
then
    # Workaround
    git status > /dev/null
    git apply --3way create.diff
    ./upgrade $1 10
fi
if [ ! -e .UPGRADE_SUCCESS ]
then
    printdiff
    echo "Fail to upgrade"
    exit 1
fi

if [[ $(git status --porcelain) == "" ]]
then
    echo Nothing to commit
    exit 0
fi
git add --all
git commit -message="Upgrade to $1"
git push $2
