---
checks:
  black: False
  isort: False
  codespell: False
  eof: False
  required_workflows: False

publish:
  docker:
    images:
      - group: geoportal
        name: camptocamp/demo-geoportal
      - group: config
        name: camptocamp/demo-config
