# yaml-language-server: $schema=https://raw.githubusercontent.com/camptocamp/c2cciutils/1.1/c2cciutils/schema.json

checks:
  codespell: False
  required_workflows: False
  setup: False
  dependabot: False
  dependabot_config: False
  black:
    ignore_patterns_re:
      - custom/custom/alembic/script\.py\.mako

version:
  branch_to_version_re:
    - from: (prod-[0-9]+-[0-9]+)
      to: \1
    - from: (int-[0-9]+-[0-9]+)
      to: \1

publish:
  pypi: false
  docker:
    images:
      - name: camptocamp/geomapfishdemo-config
      - name: camptocamp/geomapfishdemo-custom
