---
checks:
  codespell: False
  required_workflows: False
  setup: False
  dependabot: False
  black:
    ignore_patterns_re:
      - custom/custom/alembic/script\.py\.mako

version:
  branch_to_version_re:
    - from: (prod-[0-9]+-[0-9]+)
      to: \1
    - from: (int-[0-9]+-[0-9]+)
      to: \1

publish:
  docker:
    images:
      - group: config
        name: camptocamp/geomapfishdemo-config
