---
checks:
  black: False
  isort: False
  codespell: False
  eof: False
  required_workflows: False
  dependabot_config: False
  versions: False
  setup: False
  prettier: False
  print_versions:
    versions:
      - cmd:
          - python3
          - --version
        name: python
      - cmd:
          - python3
          - -m
          - pip
          - --version
        name: pip
      - cmd:
          - docker
          - --version
        name: docker

version:
  branch_to_version_re:
    - from: (prod-[0-9]+-[0-9]+)
      to: \1
    - from: (int-[0-9]+-[0-9]+)
      to: \1

publish:
  docker:
    images:
      - group: config
        name: camptocamp/geomapfishdemo-config
