# yaml-language-server: $schema=https://raw.githubusercontent.com/camptocamp/c2cciutils/1.6.23/c2cciutils/schema.json

version:
  branch_to_version_re:
    - from: (prod-[0-9]+-[0-9]+)
      to: \1
    - from: (int-[0-9]+-[0-9]+)
      to: \1

publish:
  pypi: false
  docker:
    dispatch: {}
    images:
      - name: camptocamp/geomapfishdemo-config
      - name: camptocamp/geomapfishdemo-custom
