#!/usr/bin/env python3

import subprocess
import sys


def _main() -> None:
    services = [
        s.strip()
        for s in subprocess.run(["docker-compose", "ps"], check=True, stdout=subprocess.PIPE)
        .stdout.decode("utf-8")
        .splitlines()
    ]
    errors_statuses = [s for s in services if " Exit " in s and not s.endswith(" Exit 0")]
    if errors_statuses:
        print("\n".join(errors_statuses))
        sys.exit(1)


if __name__ == "__main__":
    _main()
