#!/bin/bash -e

function publish {
    local version=$1
    shift


    echo "Deploying images to Docker Hub for tag ${version}"
    docker login --username "${DOCKER_USERNAME}" --password "${DOCKER_PASSWORD}"
    for image in $*
    do
        if [[ "${version}" != "latest" ]]
        then
            docker tag "camptocamp/demo-${image}:latest" "camptocamp/demo-${image}:${version}"
        fi
        docker push "camptocamp/demo-${image}:${version}"
    done

    (
        cd ~/
        wget https://github.com/openshift/origin/releases/download/v3.11.0/openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit.tar.gz
        tar xvfz openshift-origin-client-tools-*.tar.gz
        mv openshift-origin-client-tools-*/oc ~/bin/
    )

    oc login $OPENSHIFT_URL --username=$OPENSHIFT_USERNAME --password=$OPENSHIFT_PASSWORD
    RELEASE=`echo -n "${TRAVIS_BRANCH}" | sed -e 's/\./-/g'`
    for image in $*
    do
        oc --namespace gs-gmf-demo import-image "demo-${RELEASE}-c2cgeoportal-${image}:${version}" --scheduled true --reference-policy=local
    done
}


if [[ "${TRAVIS_PULL_REQUEST}" == "true" ]]
then
    echo "Not deploying images for pull requests"
    exit 0
fi

if [[ "${TRAVIS_BRANCH}" == "2.4" ]]
then
    publish "${TRAVIS_BRANCH}"
else
    echo "Not deploying images"
fi
