---

name: Continuous integration

on:
  push:

env:
  PROJECT: demo
  OPENSHIFT_PROJECT: gs-gmf-demo
  HELM_RELEASE_NAMES: prod-2-5
  PATH: /bin:/usr/bin:/usr/local/bin:/home/runner/.local/bin
  SUMMON_PROVIDER: /usr/local/bin/gopass

jobs:
  config:
    runs-on: ubuntu-18.04
    name: Config
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v1

      - name: Build config
        run: ./build --config env.default env.project

      - uses: camptocamp/initialise-gopass-summon-action@v1
        with:
          ci-gpg-private-key: ${{secrets.CI_GPG_PRIVATE_KEY}}
          github-gopass-ci-token: ${{secrets.GITHUB_GOPASS_CI_TOKEN}}
        if: "env.HELM_RELEASE_NAMES != ''"
      - run: scripts/publish-docker config
        if: "env.HELM_RELEASE_NAMES != ''"

  geoportal:
    runs-on: ubuntu-18.04
    name: Geoportal
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v1

      - name: Build geoportal
        run: ./build --geoportal env.default env.project

#      - uses: camptocamp/initialise-gopass-summon-action@v1
#        with:
#          ci-gpg-private-key: ${{secrets.CI_GPG_PRIVATE_KEY}}
#          github-gopass-ci-token: ${{secrets.GITHUB_GOPASS_CI_TOKEN}}
#        if: "env.HELM_RELEASE_NAMES != ''"
#      - run: scripts/publish-docker geoportal
#        if: "env.HELM_RELEASE_NAMES != ''"
