name: Continuous integration

on:
  push:
  pull_request_target:
    types: [labeled]

permissions:
  contents: write
  id-token: write
  packages: write

env:
  PROJECT: demo
  HAS_SECRETS: ${{ secrets.HAS_SECRETS }}
  # Requires CI_GPG_PRIVATE_KEY and GOPASS_CI_GITHUB_TOKEN secrets.
  OPENSHIFT_PROJECT: gs-gmf-demo
  # The release branches
  HELM_RELEASE_NAMES: prod-2-7
  SENTRY_PROJECT: geomapfish-demo
  SENTRY_ENVIRONMENT: prod-2-7
  DOCKER_BUILDKIT: '1'

jobs:
  main:
    name: Continuous integration
    runs-on: ubuntu-22.04
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v2

      - run: echo "${HOME}/.local/bin" >> ${GITHUB_PATH}
      - run: python3 -m pip install --user --requirement=ci/requirements.txt

      - name: Checks
        run: c2cciutils-checks

      - run: touch env.secrets
      - run: sed -i '/^DOCKER_TAG=/d' env.project

      - name: Build
        run: ./build --docker-compose-version-2

      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        id: tag-publish-python
        with:
          python-version: '3.11'
          update-environment: false
      - run: ${{ steps.tag-publish-python.outputs.python-path }} -m venv ${HOME}/.tag-publish
      - run: ${HOME}/.tag-publish/bin/pip install tag-publish==1.2.6
      - run: echo "${HOME}/.tag-publish/bin" >> ${GITHUB_PATH}
      - name: Publish
        run: ${HOME}/.tag-publish/bin/tag-publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: git diff --exit-code --patch > /tmp/dpkg-versions.patch || true
        if: failure()
      - uses: actions/upload-artifact@v4
        with:
          name: Update dpkg versions list.patch
          path: /tmp/dpkg-versions.patch
          retention-days: 1
        if: failure()
      - name: Create Sentry release
        uses: getsentry/action-release@v1
        with:
          environment: ${{ env.SENTRY_ENVIRONMENT }}
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: camptocamp
          SENTRY_PROJECT: ${{ env.SENTRY_PROJECT }}
        if: github.ref == 'refs/heads/prod-2-7'
