name: Continuous integration

on:
  push:
  pull_request_target:
    types: [labeled]

env:
  PROJECT: demo
  HAS_SECRETS: ${{ secrets.HAS_SECRETS }}
  # Requires CI_GPG_PRIVATE_KEY and GOPASS_CI_GITHUB_TOKEN secrets.
  OPENSHIFT_PROJECT: gs-gmf-demo
  # The release branches
  HELM_RELEASE_NAMES: prod-2-7
  SENTRY_PROJECT: geomapfish-demo
  SENTRY_ENVIRONMENT: prod-2-7
  DOCKER_BUILDKIT: '1'

jobs:
  main:
    name: Continuous integration
    runs-on: ubuntu-22.04
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v2

      - uses: camptocamp/initialise-gopass-summon-action@v2
        with:
          ci-gpg-private-key: ${{ secrets.CI_GPG_PRIVATE_KEY }}
          github-gopass-ci-token: ${{ secrets.GOPASS_CI_GITHUB_TOKEN }}
          patterns: docker
        if: env.HAS_SECRETS == 'HAS_SECRETS'

      - run: echo "${HOME}/.local/bin" >> ${GITHUB_PATH}
      - run: python3 -m pip install --user --requirement=ci/requirements.txt

      - name: Checks
        run: c2cciutils-checks

      - run: touch env.secrets
      - run: sed -i '/^DOCKER_TAG=/d' env.project

      - name: Build
        run: ./build --docker-compose-version-2

      - name: Publish
        run: c2cciutils-publish

      - run: git diff --exit-code --patch > /tmp/dpkg-versions.patch || true
        if: failure()
      - uses: actions/upload-artifact@v4
        with:
          name: Update dpkg versions list.patch
          path: /tmp/dpkg-versions.patch
          retention-days: 1
        if: failure()
      - name: Create Sentry release
        uses: getsentry/action-release@v1
        with:
          environment: ${{ env.SENTRY_ENVIRONMENT }}
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: camptocamp
          SENTRY_PROJECT: ${{ env.SENTRY_PROJECT }}
        if: github.ref == 'refs/heads/prod-2-7'
