---
name: Continuous integration

on:
  push:

env:
  PROJECT: demo
  # Requires CI_GPG_PRIVATE_KEY and GOPASS_CI_GITHUB_TOKEN secrets.
  OPENSHIFT_PROJECT: gs-gmf-demo
  # The release branches
  HELM_RELEASE_NAMES: prod-2-8

jobs:
  main:
    runs-on: ubuntu-20.04
    name: Continuous integration
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2

      - uses: camptocamp/initialise-gopass-summon-action@v2
        with:
          ci-gpg-private-key: ${{ secrets.CI_GPG_PRIVATE_KEY }}
          github-gopass-ci-token: ${{ secrets.GOPASS_CI_GITHUB_TOKEN }}
          patterns: docker
        if: env.HAS_SECRETS == 'HAS_SECRETS'

      - run: echo "${HOME}/.local/bin" >> ${GITHUB_PATH}
      - run: python3 -m pip install --user --requirement=ci/requirements.txt

      - name: Checks
        run: c2cciutils-checks

      - run: touch env.secrets

      - name: Build
        run: ./build

      - name: Publish
        run: c2cciutils-publish
