name: Rebuild

on:
  schedule:
    - cron: '30 2 * * *'

permissions:
  contents: write
  id-token: write
  packages: write

jobs:
  rebuild:
    runs-on: ubuntu-24.04
    name: Rebuild
    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:
        include:
          - branch: prod-2-7
            build_options: --docker-compose-version-2
          - branch: prod-2-8
            build_options: --docker-compose-version-2
          - branch: prod-2-9
            build_options: ''

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ matrix.branch }}

      # Requires CI_GPG_PRIVATE_KEY and GOPASS_CI_GITHUB_TOKEN secrets.
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: python3 -m pip install --requirement=ci/requirements.txt
      - name: Environment information
        run: c2cciutils-env || true

      - run: touch env.secrets
      - run: sed -i '/^DOCKER_TAG=/d' env.project

      - name: Build
        run: ./build ${{ matrix.build_options }}

      - run: python3 -m venv ${HOME}/.tag-publish
      - run: ${HOME}/.tag-publish/bin/pip install tag-publish==1.2.6
      - run: echo "${HOME}/.tag-publish/bin" >> ${GITHUB_PATH}
      - name: Publish
        run: tag-publish --type=rebuild --version=${{ matrix.branch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: git diff --exit-code --patch > /tmp/dpkg-versions.patch; git diff --color; git reset --hard || true
        if: failure()
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: Update dpkg versions list ${{ matrix.branch }}.patch
          path: /tmp/dpkg-versions.patch
          retention-days: 1
        if: failure()
