---
name: Upgrade 2.7

on:
  push:
  repository_dispatch:
    types:
      - geomapfish_2.7_updated

jobs:
  upgrade:
    runs-on: ubuntu-18.04
    name: Upgrade 2.7
    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:
        branch:
          - prod-2-7
          - prod-2-7-advance

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ matrix.branch }}
          token: ${{ secrets.GITHUB_GOPASS_CI_TOKEN }}

      - run: id
      - run: ls -als
      - run: ls -als .git
      - run: ls -als .git/objects

      - name: Update the demo
        run: >
          scripts/upgrade master origin

      - run: id
        if: failure()
      - run: ls -als
        if: failure()
      - run: ls -als .git
        if: failure()
      - run: ls -als .git/objects
        if: failure()

      - name: Push interrupted Upgrade
        run: |
          sudo chown -R $(id -u) .
          ls -als .UPGRADE*
          git add --all || true
          git add --force .UPGRADE_INSTRUCTIONS upgrade .upgrade.yaml || true
          git status
          git commit -m "Interrupted upgrade to master"
          git push --force origin HEAD:interrupted-upgrade-${{ matrix.branch }}-master
          python3 -c 'import requests
          response = requests.post(
              "https://api.github.com/repos/camptocamp/demo_geomapfish/pulls",
              json={
                "title": "Upgrade failed",
                "body": "See https://github.com/camptocamp/demo_geomapfish/actions?query=workflow%3A%22Upgrade+2.7%22",
                "head": "interrupted-upgrade-${{ matrix.branch }}-master",
                "base": "${{ matrix.branch }}",
                "maintainer_can_modify": True
              },
              headers={
                  "Accept": "application/vnd.github.v3+json",
                  "Authorization": "Bearer ${{ secrets.GITHUB_GOPASS_CI_TOKEN }}",
                  "Content-Type": "application/json",
              },
          )
          assert response.status_code < 300, response.text'
        if: failure()
      - run: ls -als .git
        if: failure()
      - run: ls -als .git/objects
        if: failure()
